INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (0,0,'Factory Equipment','90,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (0,1,'Factory Equipment','90,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (0,2,'Factory Equipment','90,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (1,0,'Factory Equipment','90,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (1,1,'Factory Equipment','90,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (1,2,'Factory Equipment','90,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (2,0,'Factory Equipment','90,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (2,1,'Factory Equipment','90,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (2,2,'Factory Equipment','90,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (3,3,'Factory Equipment','60,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (3,4,'Factory Equipment','60,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (3,5,'Factory Equipment','60,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (4,3,'Factory Equipment','60,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (4,4,'Factory Equipment','60,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (4,5,'Factory Equipment','60,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (5,3,'Factory Equipment','60,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (5,4,'Factory Equipment','60,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (5,5,'Factory Equipment','60,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (6,6,'Factory Equipment','36,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (6,7,'Factory Equipment','36,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (6,8,'Factory Equipment','36,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (7,6,'Factory Equipment','36,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (7,7,'Factory Equipment','36,000 INR'); 
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (7,8,'Factory Equipment','36,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (8,6,'Factory Equipment','36,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (8,7,'Factory Equipment','36,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (8,8,'Factory Equipment','36,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (9,9,'Factory Equipment','24,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (9,10,'Factory Equipment','24,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (10,9,'Factory Equipment','24,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (10,10,'Factory Equipment','24,000 INR');

INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (0,0,'Building','81,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (0,1,'Building','81,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (0,2,'Building','81,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (1,0,'Building','81,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (1,1,'Building','81,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (1,2,'Building','81,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (2,0,'Building','81,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (2,1,'Building','81,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (2,2,'Building','81,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (3,3,'Building','54,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (3,4,'Building','54,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (3,5,'Building','54,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (4,3,'Building','54,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (4,4,'Building','54,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (4,5,'Building','54,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (5,3,'Building','54,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (5,4,'Building','54,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (5,5,'Building','54,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (6,6,'Building','33,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (6,7,'Building','33,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (6,8,'Building','33,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (7,6,'Building','33,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (7,7,'Building','33,000 INR'); 
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (7,8,'Building','33,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (8,6,'Building','33,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (8,7,'Building','33,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (8,8,'Building','33,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (9,9,'Building','21,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (9,10,'Building','21,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (10,9,'Building','21,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (10,10,'Building','21,000 INR');



INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (0,0,'Property in Transit','99,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (0,1,'Property in Transit','99,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (0,2,'Property in Transit','99,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (1,0,'Property in Transit','99,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (1,1,'Property in Transit','99,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (1,2,'Property in Transit','99,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (2,0,'Property in Transit','99,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (2,1,'Property in Transit','99,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (2,2,'Property in Transit','99,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (3,3,'Property in Transit','63,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (3,4,'Property in Transit','63,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (3,5,'Property in Transit','63,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (4,3,'Property in Transit','63,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (4,4,'Property in Transit','63,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (4,5,'Property in Transit','63,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (5,3,'Property in Transit','63,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (5,4,'Property in Transit','63,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (5,5,'Property in Transit','63,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (6,6,'Property in Transit','42,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (6,7,'Property in Transit','42,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (6,8,'Property in Transit','42,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (7,6,'Property in Transit','42,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (7,7,'Property in Transit','42,000 INR'); 
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (7,8,'Property in Transit','42,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (8,6,'Property in Transit','42,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (8,7,'Property in Transit','42,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (8,8,'Property in Transit','42,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (9,9,'Property in Transit','32,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (9,10,'Property in Transit','32,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (10,9,'Property in Transit','32,000 INR');
INSERT INTO Quotes(Business_Value,Property_Value,Property_Type,Quotes) VALUES (10,10,'Property in Transit','32,000 INR');